### ISSUE TITLE
Do you plan to include Privacy Manifest?

### ISSUE THREAD

**Issue by goodarmen96** [moyasar/moyasar-ios-pod#10]
According to [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files), I think this library may also require a Privacy Manifest for the upcoming app review in Spring 2024.

Do you have any plans to add a Privacy Manifest or to have a claim that this library actually does not need a Privacy Manifest?

Thank you very much!

**Comment by AbdulazizAlrabiah** [comment]
Hi 👋

Thank you for reporting it! The file has been added 👌
